// Top-level build file where you can add configuration options common to all sub-projects/modules.
plugins {
    // Plugins automatically generated by TLGradle.kt
    alias(libs.plugins.android.application) apply false
}

tasks.register<Delete>("clean") {
    delete(rootProject.layout.buildDirectory)
}
